# Logging
logging:
  level:
    io.r2dbc.postgresql.QUERY: DEBUG # for queries
    io.r2dbc.postgresql.PARAM: DEBUG # for parameter

# Swagger
springdoc:
  swagger-ui:
    path: /swagger-doc/swagger-ui.html
  show-actuator: true
  api-docs:
    path: /swagger-doc/v3/api-docs
    groups:
      enabled: true

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: info, health, openapi, swagger-ui
  info:
    env:
      enabled: true
  endpoint:
    info:
      enabled: true
    health:
      enabled: true

# info properties
info:
  app:
    name: ${spring.application.name}
    version: 1.0.0
    description: Product microservice
  svc:
    port: ${server.port}


# eureka config
eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance-id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/